org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.233
neo_version_range=[21.1.233,)
loader_version_range=[4,)

createVersion=6.0.10-280
flywheelVersion=1.0.6
ponderVersion=1.0.82

jei_version=19.25.0.322
kubejs_version=2101.7.2-build.368
kubejs_version_range=[2101.7.2-build.368,)
kubejs_create_version=2101.3.1-build.18
kubejs_create_version_range=[2101.3.1-build.18,)
create_version_range=[6.0.10,)
registrateVersion=MC1.21-1.3.0+67
tfmg_version=1.2.4a

mod_id=tfmgjs
mod_name=KubeJS TFMG
mod_license=MIT NON-AI
mod_version=1.21.1-1.1.0
mod_group_id=dev.wolfieboy09.tfmgjs
mod_authors=Wolfieboy09
mod_description=Adds KubeJS integration for Create: The Factory Must Grow
