modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/KubeJS-TFMG/issues"

[[mods]]
modId="tfmgjs"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://github.com/wolfieboy09/KubeJS-TFMG/blob/main/versions.json"
displayURL="https://github.com/wolfieboy09/KubeJS-TFMG"

logoFile="tfmgjs.png"

authors="${mod_authors}"
description='''${mod_description}'''
[[dependencies.tfmgjs]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfmgjs]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfmgjs]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.i-59,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfmgjs]]
    modId="kubejs"
    mandatory=true
    versionRange="[1902.6.2-build.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tfmgjs]]
    modId="tfmg"
    mandatory=true
    versionRange="[0.9.3-1.19.2,)"