modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/wolfieboy09/KubeJS-TFMG/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/wolfieboy09/KubeJS-TFMG/refs/heads/1.21.1/versions.json"
displayURL="https://github.com/wolfieboy09/KubeJS-TFMG"
logoFile="tfmgjs.png"
authors="${mod_authors}"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="${neo_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs"
type="required"
versionRange="${kubejs_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="kubejs_create"
type="required"
versionRange="${kubejs_create_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="tfmg"
type="required"
versionRange="[${tfmg_version},)"
ordering="NONE"
side="BOTH"
